name: detect drifts in aws resources
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  id-token: write
  contents: read

jobs:
  drift-detect:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: terraform
      AWS_REGION: us-east-1
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      bucket: ${{ secrets.BACKEND_S3_BUCKET }}
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }} 

      - name: setup terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Make the script executable
        run: chmod +x scripts/terraform_detector.sh

      - name: Initialize terraform
        run: terraform init -input=false -backend-config="bucket=${{ secrets.BACKEND_S3_BUCKET }}"
      
      - name: Run the drift detection script
        run: ./scripts/terraform_detector.sh

      - name: Upload plan output artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-output
          path: terraform/terraform-plan-output.txt